// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Demo from "../components/Demo.js";
import * as React from "react";

function Main$page(props) {
  return React.createElement(Demo.make, {});
}

var page = Main$page;

export {
  page ,
}
/* Demo Not a pure module */
